import os
import copy

BIN_DIR = os.environ['BIN_DIR'];
LIB_DIR = os.environ['LIB_DIR'];

env = DefaultEnvironment().Clone()
SOURCES = [
  'vnc.c' ,
  'main_loop_vnc.c' ]

env.Library(os.path.join(LIB_DIR, 'awtk_vnc'), SOURCES)

